pipeline {
    agent { docker { image 'python:3.10.7-alpine' } }
    stages {
        stage('Pre Build') {
            steps {
                echo 'Pre Build'
            }
        }        
        stage('Checkout Code') {
            steps {
                echo 'Code is already checked out'
            }
        }
        stage('Build') {
            steps {
                sh 'python --version'
                sh 'pwd'
                sh 'cd project/code'
                sh 'ls'
                sh 'python *.py'
            }
        }
    }
    post { 
        always { 
            echo 'Post Build'
        }
    }
}
