import jenkins.model.*
//jenkins = Jenkins.instance

pipeline {
    //agent { docker { image 'python:3.10.7-alpine' } }
    agent { docker { image 'eamonwoortman/alpine-python-curl-zip' } }
    
    stages {
        stage('Pre Build') {
            steps {
                echo 'Pre Build'
                echo "GITHUB_PR_NUMBER=${env.GITHUB_PR_NUMBER}"
                echo "GITHUB_PR_STATE=${env.GITHUB_PR_STATE}"
                echo "GITHUB_PR_SHORT_DESC=${env.GITHUB_PR_SHORT_DESC}"
                echo "GITHUB_PR_TITLE=${env.GITHUB_PR_TITLE}"
                echo "GITHUB_PR_URL=${env.GITHUB_PR_URL}"
                sh 'python --version'
                sh 'pwd'
            }
        }        
        stage('Checkout Code') {
            steps {
                echo 'Code is already checked out'
            }
        }
        stage('Build and Run Code') {
            steps {
                dir('project/code')
                {
                    sh 'ls'
                    sh 'python *.py'
                }
            }
        }
        stage('Run Unit Tests') {
            steps {
                dir('project/tests')
                {
                    sh 'ls'
                    sh 'python *.py'
                }
            }
        }
    }
    
    post { 
        success {
            script {
                echo 'Build Passed'
                if (env.GITHUB_PR_NUMBER) {
                    withCredentials([string(credentialsId: 'github_token', variable: 'GITHUB_TOKEN')]) {
                        sh """
                        curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" --data '{"body": "PR Jenkins Build Passed"}' https://api.github.com/repos/salmanmak1/tsofenaws/issues/${GITHUB_PR_NUMBER}/comments
                        """
                    }
                }
            }
        }
        failure {
            script {
                echo 'Build Failed'
                if (env.GITHUB_PR_NUMBER) {
                    withCredentials([string(credentialsId: 'github_token', variable: 'GITHUB_TOKEN')]) {
                        sh """
                        curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" --data '{"body": "PR Jenkins Build Failed"}' https://api.github.com/repos/salmanmak1/tsofenaws/issues/${GITHUB_PR_NUMBER}/comments
                        """
                    }
                }
            }
        }
        always { 
            echo 'Post Build Cleaning...'
        }
    }
}
